version: '3.8'

services:
  db:
    image: postgres:13.7-alpine
    ports:
      - "6541:5432"
    container_name: shareIt-db
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  server:
    build: shareIt-server
    #image: server:latest
    container_name: shareIt-server-container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  gateway:
    build: shareIt-gateway
    #image: gateway:latest
    container_name: shareIt-gateway-container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090